import type { NextPage } from "next";
import Head from "next/head";
import { GlobalStyle } from "../styles/Global";
import { Container } from "../styles/MainPage";
import { Appbar } from "./components/Appbar";
import { Principal } from "./components/Principal";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Rique Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@600;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <Appbar />
      <Principal />

      <GlobalStyle />
    </Container>
  );
};

export default Home;
